import { DigitalAsset } from '@/types';

export const DIGITAL_ASSETS: DigitalAsset[] = [
  {
    id: 'btc-fraction',
    name: 'Bitcoin',
    symbol: 'BTC',
    icon: '₿',
    priceInPoints: 10000,
    category: 'crypto',
    description: '0.0001 BTC - Uma fração de Bitcoin',
    available: true,
  },
  {
    id: 'eth-fraction',
    name: 'Ethereum',
    symbol: 'ETH',
    icon: 'Ξ',
    priceInPoints: 5000,
    category: 'crypto',
    description: '0.001 ETH - Uma fração de Ethereum',
    available: true,
  },
  {
    id: 'sol-token',
    name: 'Solana',
    symbol: 'SOL',
    icon: '◎',
    priceInPoints: 2000,
    category: 'crypto',
    description: '0.01 SOL - Tokens Solana',
    available: true,
  },
  {
    id: 'short-token',
    name: 'Short Token',
    symbol: 'SHORT',
    icon: '💘',
    priceInPoints: 500,
    category: 'token',
    description: '10 SHORT - Token nativo do app',
    available: true,
  },
  {
    id: 'love-nft',
    name: 'Love Badge NFT',
    symbol: 'NFT',
    icon: '🎖️',
    priceInPoints: 3000,
    category: 'nft',
    description: 'Badge exclusivo de colecionador',
    available: true,
  },
  {
    id: 'streak-nft',
    name: 'Streak Master NFT',
    symbol: 'NFT',
    icon: '🔥',
    priceInPoints: 7500,
    category: 'nft',
    description: 'NFT raro para os melhores jogadores',
    available: true,
  },
  {
    id: 'usdt-token',
    name: 'Tether',
    symbol: 'USDT',
    icon: '₮',
    priceInPoints: 1000,
    category: 'crypto',
    description: '$1 USDT - Stablecoin',
    available: true,
  },
  {
    id: 'doge-token',
    name: 'Dogecoin',
    symbol: 'DOGE',
    icon: '🐕',
    priceInPoints: 300,
    category: 'crypto',
    description: '10 DOGE - Much wow',
    available: true,
  },
];
